name: Get Citation Data

on:
  page_build:
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 指定Python版本
    - name: Install Reqs
      run: |
        python -m pip install --upgrade pip
        python -m venv myenv
        source myenv/bin/activate
        pip install -r google_scholar_crawler/requirements.txt
    - name: Run
      run: |
        cd google_scholar_crawler
        source ../myenv/bin/activate
        python main.py
        cd ../results
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git add *.json
        git commit -m "Updated Citation Data"
        git push "${remote_repo}" HEAD:google-scholar-stats --force
      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
