name: Get Citation Data

on:
  page_build:
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python and Virtual Environment
        run: |
          sudo apt-get update
          sudo apt-get install python3-venv
      - name: Setup Virtual Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r google_scholar_crawler/requirements.txt
      - name: Run Script
        run: |
          source venv/bin/activate
          python google_scholar_crawler/main.py
      - name: Commit and Push Results
        run: |
          cd ./google_scholar_crawler/results
          git init
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git add *.json
          git commit -m "Updated Citation Data"
          git push "${remote_repo}" HEAD:google-scholar-stats --force
      env:
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
